name: Secret Manager (access from Google SM)
on:
  workflow_dispatch:

jobs:
  secret-manager-access:
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    # env:
      # GOOGLE: ${{ secrets.GOOGLE_CREDENTIALS }}
    steps:
    - uses: 'actions/checkout@v4'

    - uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
    - id: 'secrets'
      uses: 'google-github-actions/get-secretmanager-secrets@v2'
      with:
        secrets: |-
          API_KEY:${{ secrets.PROJECT_ID }}/API_KEY
    - name: Print the Secret
      run: echo ${{ steps.secrets.outputs.API_KEY }} | sed 's/./& /g'